version: '3.8'

services:
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: postgres
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    deploy:
      replicas: 1

  web:
    build:
      context: .          # Build from current directory
      dockerfile: Dockerfile  # Ensure this exists
    environment:
      DB_NAME: postgres
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_PORT: 5432
      SECRET_KEY: 'django-production-secret-key-change-this'
      DEBUG: 'False'
    ports:
      - "8000:8000"
    depends_on:
      - db
    networks:
      - app-network
    deploy:
      replicas: 2
      update_config:
        parallelism: 1
        delay: 10s
      restart_policy:
        condition: on-failure

volumes:
  postgres_data:

networks:
  app-network:
    driver: overlay

